#!/usr/bin/env bash
# filepath: /home/oniji/holbertonschool-network/basics_0/5-is_the_host_on_the_network

if [ $# -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

ping -c 5 "$1"
