#!/usr/bin/env bash
# This script changes localhost to 127.0.0.2 and facebook.com to 8.8.8.8 in /etc/hosts

sudo sed -i '/localhost/d' /etc/hosts
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null

sudo sed -i '/facebook.com/d' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
